### ISSUE TITLE
image with alpha not working

### ISSUE THREAD

**Issue by nadangergeo** [daneden/Basehold.it#28]
Hi!

http://basehold.it/i/24/255/0/0/0.85 returns 404

Nice tool btw! It was exactly what I was searching for when I realized there should be a faster way than booting up PS and creating a background.

**Comment by gsklee** [comment]
@daneden Anything we can do to help fix this?

**Comment by daneden** [comment]
I think this should be fixed now; Basehold.it has essentially been totally rewritten 😄

**Comment by nadangergeo** [comment]
Sweeeet! Nice work! :D

Hälsningar,
Nadan Gergeo
